run:
  timeout: 5m
linters:
  enable:
    - asciicheck
    - bidichk
    - decorder
    - dogsled
    - dupl
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - lll
    - misspell
    - nakedret
    - nestif
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - stylecheck
    - tenv
    - thelper
    - unconvert
    - whitespace
    - wrapcheck
  disable:
    - depguard
    - gomnd
    - structcheck
issues:
  exclude-rules:
    - linters:
        - forbidigo
      path: internal/app/migrate.go
    - linters:
        - goheader
      path: _test\.go
    - linters:
        - revive
      name: dot-imports
      path: _test\.go
    - linters:
        - revive
      name: blank-imports
      path: internal/app/migrate.go
linters-settings:
  goheader:
    values:
      const:
        DEVELOPER: Michael Fero
    template: |-
      Copyright © {{ YEAR }} {{ DEVELOPER }}

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
